### ISSUE TITLE
Merge latest code from @kanjitalk755

### ISSUE THREAD

**Issue by ianfixes** [emaculation/SheepShaver#14]
Refer to discussion at:
https://github.com/kanjitalk755/macemu/issues/14

Bring in these edits, as they are the most current development of this project.

**Comment by retokromer** [comment]
@ianfixes When do you plan do to this? (I am asking because I would like to work on https://github.com/emaculation/SheepShaver/issues/8, but I don’t like to do useless work…)

**Comment by ianfixes** [comment]
I'm talking with one of the other devs about this.  I've just discovered that there are a LOT of symlinked files between the 2 projects, and so at the moment the only sensible thing to do appears to be splitting off those common elements into a standalone `libBasiliskII` (or some such) and including it from both projects.

This is more or less the kind of rabbit hole I expected to encounter, but I'm prepared to sort it out.  

In the immediate term, my plan is to start over from @kanjitalk755's repo (fix the symlinks, split the resulting repo), and then merge in the work that we've done here.  I'm going to peek at that now

**Comment by retokromer** [comment]
Thank you very much indeed for the information!

**Comment by ianfixes** [comment]
I've captured stuff in #15 and my plan for now is to avoid accepting requests on any of those files unless/untill we establish a way to build those all from a shared location.  That's going to put a lot of focus on refactoring instead of moving forward with new features, but I don't think the current setup is healthy for long-term maintenance.

**Comment by retokromer** [comment]
>I don't think the current setup is healthy for long-term maintenance.

I fully agree with you! I did add to https://github.com/emaculation/SheepShaver/issues/15 some historical context which could be useful.

**Comment by ianfixes** [comment]
This is done, but it's very likely that I broke the builds in the process and will have to fix those as a top priority.

**Comment by DrLex0** [comment]
@ianfixes Can you also include the latest commit that provides a different icon for SheepVM bundles?

**Comment by ianfixes** [comment]
Hmm, looks like that got submitted after I started work on combining repos and splitting projects.  I'm just going to pull the files in directly for now, and then my main concern will be the build tasks listed in https://github.com/kanjitalk755/macemu/issues/14

**Comment by ianfixes** [comment]
Done: https://github.com/emaculation/SheepShaver/commit/07cac572f942884801ce2cb78c054caf3d6ead67
